# -*- coding: utf-8 -*-
"""1063

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6yfUeDqYFsbPr-k4nVn9HDiP5xjo6lw
"""

!apt-get update
!apt-get install openjdk-11-jdk -y
!java -version

!rm -f apache-jmeter-5.6.2.tgz

!wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz

!ls -lh apache-jmeter-5.6.2.tgz

!tar -xzf apache-jmeter-5.6.2.tgz

!mv apache-jmeter-5.6.2 /opt/jmeter

!ls /opt/jmeter

!ls -lh apache-jmeter-5.6.2.tgz

!tar -xzf apache-jmeter-5.6.2.tgz

!tar -xzf apache-jmeter-5.6.2.tgz

# Move JMeter to /opt directory
!mv apache-jmeter-5.6.2 /opt/jmeter

# Verify installation
!ls /opt/jmeter

!ls -l /opt/jmeter

!/opt/jmeter/bin/jmeter -v

# Set JMeter environment variables
import os

os.environ["JMETER_HOME"] = "/opt/jmeter"
os.environ["PATH"] += os.pathsep + "/opt/jmeter/bin"

# Verify if JMeter runs
!$JMETER_HOME/bin/jmeter --version

from google.colab import files
uploaded = files.upload()

!ls -l

! /opt/jmeter/bin/jmeter -n -t test-plan.jmx -l result.jtl

!cat result.jtl

from google.colab import files
files.download('result.jtl')

!mv result.jtl jmeter_results.jtl

!ls -l jmeter_results.jtl

!git config --global user.name "KrishnaBalaji1063"
!git config --global user.email "kchintha4@gitam.in"

!git clone https://github.com/KrishnaBalaji1063/MID.git

!mv jmeter_results.jtl MID/

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd MID

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/MID

!git add .

!git commit -m "Added JMeter test results"

!git config --global user.name "KrishnaBalaji1063"
!git config --global user.email "kchintha4@gitam.in"

ls -l /content/MID

!git clone https://github.com/KrishnaBalaji1063/MID.git

!ls -l

!find /content -name "results.csv"

!ls -l

!find /content -name "results.csv"

!cp jmeter_results.jtl results.csv

!ls -l results.csv

!mv results.csv MID/

!ls -l MID/

!ls -l

!mv view_results.csv results.csv

!mv results.csv MID/

!ls -l MID/

!ls -l

!mkdir MID  # Create MID directory
!mv results.csv MID/  # Move results.csv inside MID/

!ls -l MID/

!git push https://KrishnaBalaji1063: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@github.com/KrishnaBalaji1063/MID.git main